spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shopmedb
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
    show-sql: true

